import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Topbar from "@/components/topbar";
import Middle from "@/components/middle";
import Header from "@/components/header";
import Hero from "@/components/hero";

import Footer from "@/components/footer";
import ProductsPage from "@/components/OurProducts";
import ContactSection from "./Contact/page";
import Company from "@/components/company";
import FeatureProduct from "@/components/FeatureProduct";
import Shop from "./Shop/page";
import TopCategories from "@/components/TopCategories";
import Style from "@/components/style";







const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Header/>
       {children}

        <Topbar/>
       <Middle />
       <Hero/>
       <Company/>
       <FeatureProduct/>
       <TopCategories/>
       <Style/>

       
     
<ProductsPage/>
    <Shop/>
     <ContactSection/>
       
       <Footer/>
      </body>
    </html>
  );
}
